#' @keywords internal
#' @noRd
utils::globalVariables(c(
  ".",
  ".data",
  "compound_id",
  "Alignment ID",
  "Annotation tag (VS1.0)",
  "Average RI",
  "Average Rt(min)",
  "EI spectrum",
  "Metabolite name",
  "Total score",
  "RT similarity",
  "INCHIKEY",
  "nonzero",
  "id",
  "mz_bin",
  "intensity",
  "known",
  "RI",
  "estimated_Mref",
  "detected_neutral_losses",
  "inferred_functional_groups",
  "compound_class",
  "V1",
  "V2",
  "cluster"
  ,
  "method",
  "value",
  "metric",
  "threshold",
  "fdr",
  "mz",
  "mref_confidence",
  "derivatization_type",
  "deriv_score_tms",
  "deriv_score_tbdms",
  "deriv_i73",
  "deriv_i147",
  "deriv_i115",
  "deriv_i57",
  "top_typical_losses",
  "top_typical_losses_consistent",
  "n",
  "n_known",
  "level",
  "cum",
  "part",
  "mid",
  "label",
  "abs_int",
  "alpha",
  "vjust"
))
